version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./registry/auth:/auth
      - ./registry/data:/var/lib/registry
    networks:
      - registry-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - AUTH_FILE=/auth/htpasswd
      - REGISTRY_URL=http://registry:5000
    volumes:
      - ./registry/auth:/auth
      - ./backend/data:/data
    networks:
      - registry-net
    depends_on:
      - registry

  ui:
    build: ./ui
    ports:
      - "3000:80"
    networks:
      - registry-net
    depends_on:
      - backend

networks:
  registry-net:
    driver: bridge
